name: test_reflectable
version: 2.0.0-dev.2.0
description: >
  This package contains tests which depend on package reflectable and
  which are built by the code generation support offered by that
  package. It is not intended to be useful for other purposes than
  testing package reflectable.
author: The Dart Team <dart@google.com>
homepage: https://www.github.com/dart-lang/test_reflectable
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  reflectable: # ^2.0.0-pre.2.0
    path: ../reflectable/reflectable
  build_runner: ^0.7.0
  glob: ^1.1.5
dev_dependencies:
  unittest: ^0.11.0
transformers:
- $dart2js:
    $include: []
